// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE3579DX30_R65TrtISmySnVkbbfzYmpg',
    appId: '1:845237595613:web:673f0fc44ab3af47515a34',
    messagingSenderId: '845237595613',
    projectId: 'cyscom-mod',
    authDomain: 'cyscom-mod.firebaseapp.com',
    databaseURL: 'https://cyscom-mod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cyscom-mod.appspot.com',
    measurementId: 'G-T66HWV4FN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MEHXFsLgoENIybGkPeOyCjomhbTTSSw',
    appId: '1:845237595613:android:bcabb3d098c90949515a34',
    messagingSenderId: '845237595613',
    projectId: 'cyscom-mod',
    databaseURL: 'https://cyscom-mod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cyscom-mod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmFUD4GSKv6jEssGBOUZVJcQ6OsZKl04',
    appId: '1:845237595613:ios:f496b0c2aef6a307515a34',
    messagingSenderId: '845237595613',
    projectId: 'cyscom-mod',
    databaseURL: 'https://cyscom-mod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cyscom-mod.appspot.com',
    iosBundleId: 'com.example.modAppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmFUD4GSKv6jEssGBOUZVJcQ6OsZKl04',
    appId: '1:845237595613:ios:f496b0c2aef6a307515a34',
    messagingSenderId: '845237595613',
    projectId: 'cyscom-mod',
    databaseURL: 'https://cyscom-mod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cyscom-mod.appspot.com',
    iosBundleId: 'com.example.modAppl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE3579DX30_R65TrtISmySnVkbbfzYmpg',
    appId: '1:845237595613:web:14862b441a14d503515a34',
    messagingSenderId: '845237595613',
    projectId: 'cyscom-mod',
    authDomain: 'cyscom-mod.firebaseapp.com',
    databaseURL: 'https://cyscom-mod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cyscom-mod.appspot.com',
    measurementId: 'G-ZZBGQZ7MCS',
  );

}